version: "3"
services:
  mongodb:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=dbUser
      - MONGO_INITDB_ROOT_PASSWORD=test123
    ports:
      - "27017-27019:27017-27019"
  nats-stream:
    image: "nats-streaming"
    expose:
      - "4223"
    ports:
      - "4223:4222"
      - "8223:8222"
